[build]
  publish = "build/client"
  command = "npm run build"

[functions]
  directory = "build/server"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200
  force = true

[build.environment]
  NODE_VERSION = "20"

# Para manejar las rutas de React Router
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"